# ESP32-S3-Touch-LCD-7
substitutions: !include include/substitutions.yaml

packages:
  hardware: !include include/hardware.yaml
  button: !include include/button.yaml
  globals: !include include/globals.yaml
  interval: !include include/interval.yaml
  text_sensor: !include include/text_sensor.yaml
  sensor: !include include/sensor.yaml
  # binary_sensor: !include include/binary_sensor.yaml
  switch: !include include/switch.yaml
##  online_image: !include include/online_image.yaml
##  select: !include include/select.yaml
  number: !include include/number.yaml
  script: !include include/script.yaml
  lvgl: !include include/lvgl.yaml




